MicroFocus/ppm-octane-connector

- config/deploy.info
- src/com/ppm/integration/agilesdk/connector/octane/OctaneConstants.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.properties
- src/com/ppm/integration/agilesdk/connector/octane/OctaneReleaseIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneSprintIExternalTask.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneTimeSheetIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneUSIExternalTask.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneWorkPlanIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/Client.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Release.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Releases.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Sprint.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Sprints.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkItemFeature.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkItemRoot.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkItemStory.java
- test/com/ppm/integration/agilesdk/connector/octane/OctaneReleaseIntegrationTest.java
> fix defects and make work plan use Sprint-US structure

- src/com/ppm/integration/agilesdk/connector/octane/OctaneEntityDropdown.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneWorkPlanIntegration.java
error tip display when authentication failed
> show tip when authentication error

- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.properties
- src/com/ppm/integration/agilesdk/connector/octane/OctaneWorkPlanIntegration.java
it's wrong to sort sprints by id as sprint1 may have bigger id than sprint2's
> Defect#correct out of order after workplan sycn

- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.properties
- src/com/ppm/integration/agilesdk/connector/octane/OctaneWorkPlanIntegration.java
> correct wrong labels

- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/ReleaseTeams.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Releases.java
- src/com/ppm/integration/agilesdk/connector/octane/model/SharedSpaces.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Sprints.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Teams.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkSpaces.java
resolve the defect about not handle the authentication failed situation
> Fix authentication defect

- src/com/ppm/integration/agilesdk/connector/octane/OctaneConstants.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.properties
add new fields in integration landing page
> US#80003 add new field in integrationconnector class

- src/com/ppm/integration/agilesdk/connector/octane/OctaneReleaseIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/EpicAttr.java
- src/com/ppm/integration/agilesdk/connector/octane/model/EpicCreateEntity.java
- src/com/ppm/integration/agilesdk/connector/octane/model/EpicEntity.java
create epic in octane;
get epic pahse api;
get epic parent api;
> US#79010-epic-wizard-step3-octane-code:

- src/com/ppm/integration/agilesdk/connector/octane/OctaneReleaseIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkItemEpic.java
- test/com/ppm/integration/agilesdk/connector/octane/ClientPublicAPITest.java
@Elva-Zhu 
@qish-hl 
@LuChunQi 
@etiennec
> Us#76003 background service to fetch the epic items information

- src/com/ppm/integration/agilesdk/connector/octane/OctaneConstants.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.java
- src/com/ppm/integration/agilesdk/connector/octane/OctanePortfolioEpicIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneReleaseIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/OnctaneIntegrationHelper.java
- src/com/ppm/integration/agilesdk/connector/octane/model/EpicEntity.java
create an OctanePortfolioEpicIntegration.java which implement PortfolioEpicIntegration interface to support creating epic in octane
> To support portfolio epic

- src/com/ppm/integration/agilesdk/connector/octane/OctanePortfolioEpicIntegration.java
move octane epic URI to connector
> Us#92012 refactor connector

- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.java
- src/com/ppm/integration/agilesdk/connector/octane/OctanePortfolioEpicIntegration.java
modified fields in landing page
> Us#107014 landing page refactor

- src/com/ppm/integration/agilesdk/connector/octane/OctaneWorkPlanIntegration.java
from task's mapping configuration
> get Agile Entity information

- src/com/ppm/integration/agilesdk/connector/octane/OctaneFunctionIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneTimeSheetIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneWorkPlanIntegration.java
user can choose to use global proxy when user set com.kintana.core.server.HTTP_PROXY_URL in server.conf
> defect#63002 support use global proxy

- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- test/com/ppm/integration/agilesdk/connector/octane/OctaneAgileDataIntegrationTest.java
1.fix wrong url parameter
2.fix junit test
> defect#fix test case

- src/com/ppm/integration/agilesdk/connector/octane/OctaneIntegrationConnector.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneRequestIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/FieldInfo.java
To support to get octane entity fields
> Request octane mapping

- src/com/ppm/integration/agilesdk/connector/octane/OctaneRequestIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
1.retry when occur socket exeception when authentication
2.refector the method to generate returned Map<String, List<FieldValue>> in getEntity
> US#167022 create entity error

- src/com/ppm/integration/agilesdk/connector/octane/OctaneConstants.java
- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
US#373001 refactor code for getting octane users
> US#373001 refactor code for getting octane users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
US#379001 refactor parameter of getAgileUsers to be more generic
> US#379001 refactor parameter of getAgileUsers to be more generic

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
US#369007 add security  group to octane users
> US#369007 add security  group to octane users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/OctaneProject.java
- src/com/ppm/integration/agilesdk/connector/octane/model/OctaneSyncUserConfiguration.java
- src/com/ppm/integration/agilesdk/connector/octane/model/UserSecurityConfiguration.java
US#369007 add product license to users
> US#369007 add product license to users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
US#395037 add limited size to get octane users
> US#395037 add limited size to get octane users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
US#395037 get license type of users and modify users security groups and license
> US#395037 get license type of users and modify users security groups and license

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
US#406001 get activity_level of workspace users
> US#406001 get activity_level of workspace users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
Defect#409010 fix update user license type(DO NOT MERGE)
> Defect#409010 fix update user license type(DO NOT MERGE)

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
Defect#428044 fix index error when sync users
> Defect#428044 fix index error when sync users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/UserSecurityConfiguration.java
US#443014_sync_shared_space_level_users
> US#443014_sync_shared_space_level_users

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
US#450003 remove workspace code
> US#450003 remove workspace code

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Permission.java
- src/com/ppm/integration/agilesdk/connector/octane/model/PermissionData.java
- src/com/ppm/integration/agilesdk/connector/octane/model/Role.java
- src/com/ppm/integration/agilesdk/connector/octane/model/RoleData.java
- src/com/ppm/integration/agilesdk/connector/octane/model/SharedSpaceUser.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkspaceInfo.java
- src/com/ppm/integration/agilesdk/connector/octane/model/WorkspaceRole.java
Defect#449014 fix performance issue when sync large number of users
> Defect#449014 fix performance issue when sync large number of users

- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
Defect#443014 fix log is null when synchronization users
> Defect#443014 fix log is null when synchronization users

- src/com/ppm/integration/agilesdk/connector/octane/OctanePortfolioIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
> update request data

- src/com/ppm/integration/agilesdk/connector/octane/OctaneConstants.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
US#632001_add_strategic_field_for_octane_synchronization
> US#632001_add_strategic_field_for_octane_synchronization

- env.bat
- src/com/ppm/integration/agilesdk/connector/octane/OctaneRequestIntegration.java
1. split in clause to 500 items
2. set build java version to 1.8
> Defect#1207050ExternalSyncServiceConnectionReset

- src/com/ppm/integration/agilesdk/connector/octane/OctaneRequestIntegration.java
root cause: encounter 414 Request-URI Too Large error when the url contains too many user ids
solution: split user ids into multiple groups, query users by multiple requests
> Defect#1587227

- src/com/ppm/integration/agilesdk/connector/octane/OctaneUserIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
- src/com/ppm/integration/agilesdk/connector/octane/model/SharedSpaceUser.java
US#1674478-spm-syncup-user-add-language
- add language field from API
> US#1674478-spm-syncup-user-add-language

- src/com/ppm/integration/agilesdk/connector/octane/OctaneRequestIntegration.java
US#1675010_support_attachment_sync_from_octane_to_PPM
> US#1675010_support_attachment_sync_from_octane_to_PPM

- src/com/ppm/integration/agilesdk/connector/octane/OctaneRequestIntegration.java
- src/com/ppm/integration/agilesdk/connector/octane/client/ClientPublicAPI.java
Defect#1729860_fix_share_epic_not_display_issue
> Defect#1729860_fix_share_epic_not_display_issue
